# Generated by Django 2.2.5 on 2021-03-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('User_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
                ('phonenumber', models.IntegerField(default=0, unique=True)),
                ('Age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dailystatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_visited', models.CharField(max_length=100, null=True)),
                ('total_persons_approched', models.IntegerField(default=0)),
                ('number_converted', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('User_f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salestrackingapp.Userdata')),
            ],
        ),
        migrations.CreateModel(
            name='customerdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('DOB', models.CharField(max_length=100, null=True)),
                ('Age', models.CharField(max_length=100, null=True)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'FeMale'), ('other', 'Other')], default='male', max_length=50)),
                ('Family_member', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('Is_client', models.BooleanField(default=False)),
                ('User_c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salestrackingapp.Userdata')),
            ],
        ),
    ]
